FROM oven/bun:slim AS builder
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install
COPY . .
RUN bun run build


FROM oven/bun:slim AS runner
WORKDIR /app

# Set the environment variable to production to optimize the application for production use
ENV NODE_ENV="production"

# Allow the server to be accessible from outside the container
ENV HOSTNAME=0.0.0.0     

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["bun", "server.js"]