import "./globals.css";
import { type Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import { FloatingBackground } from "@components/floating-background";
import { cn } from "@lib/utils";
import { Toaster } from "sonner";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", inter.className, "font-sans", geist.variable)}>
      <body className="flex min-h-screen items-center justify-center text-primary-foreground">
        <FloatingBackground />

        <main>
          {children}
        </main>

        <Toaster richColors duration={3000} position="top-center" />
      </body >
    </html >
  );
}
