FROM oven/bun:1.3.14-slim AS builder
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

ENV DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

RUN bun run build


FROM oven/bun:1.3.14-slim AS runner
WORKDIR /app

COPY --from=builder /app/out ./ 
COPY --from=builder /app/drizzle ./drizzle/
COPY --from=builder /app/start.sh ./

RUN apt-get update && apt-get install -y postgresql-client

EXPOSE 3002

RUN chmod 700 ./start.sh

CMD ["./start.sh"]
